### ISSUE TITLE
Better protection for private attributes of InferenceProblem

### ISSUE THREAD

**Issue by aklawonn** [BAMresearch/probeye#10]
Currently, you can modify the private attributes of InferenceProblem (such as InferenceProblem._parameters) via the corresponding properties. This means, for example, you modify InferenceProblem._parameters['a'] via
`InferenceProbelm.parameters['a'] = InferenceProbelm.parameters['b']`
This should not be possible in order to prevent messing with private attributes. Preferable, there should be an error raised, if something like this is tried.

**Comment by TTitscher** [comment]
Three ideas, where I would prefer number 2:

1. Over in BayesInference, we wanted the user to explicity create parameters via a `.define()` instead of the `__setitem__` method and implemented the latter one [here](https://github.com/BAMresearch/BayesianInference/blob/master/bayes/parameters.py#L30-L32). You could also override the `__setitem__` with an exception like _Please use InferenceProblem.add_parameter(...) to define new parameters._ or not inherit from `dict` in the first place. 

2. Another solution is a design modification to basically move all the code (mostly for verification) of `InferenceProblem.add_parameter` into `Parameters.__setitem__`. In that case, it would be no difference which method is called, `add_parameter` could even be removed. However, that is not trivially possible as [`InferenceProblem._add_prior`](https://github.com/BAMresearch/probeye/blob/70cbcb3e5c7a72594dbfbe9433fc0046ed2c75f3/probeye/definition/inference_problem.py#L359-L360) is called _within_ `add_parameter`... 

3. `_parameters` is purely private and you forward some method the user may be interested in. So instead of
~~~py
prm = problem.parameters["a"]
if prm.role == "latent":
   something[prm.index] = 6174
~~~
you provide
~~~py
if problem.parameter_is_latent("a"):
    something[problem.parameter_get_index("a")] = 6174
~~~

**Comment by aklawonn** [comment]
I implemented a forth way, where the attributes of ParameterProperties are made private. Additionally, I added corresponding properties to the ParameterProperties-class. This combination allows to access but not modify these attributes from outside. However, when you try to modify them, you will get a standard AttributeError raised. To modify the error-message (and make it more informative for the user), I also implemented setter-decorators in the ParameterProperties-class, which give you a more informative error-message, when you try to manipulate these attributes from outside.
