### ISSUE TITLE
Implement correlation framework

### ISSUE THREAD

**Issue by aklawonn** [BAMresearch/probeye#9]
Currently, there is no way to account for correlations between measurements. Corresponding classes and/or methods have to be provided in the future.

**Comment by rozsasarpi** [comment]
Ideally it would be more general and would not only cover possible dependencies between measurements (measurement uncertainties) but also between model predictions. The latter is the more relevant one in my opinion (based on how we define/interpret measurement and model prediction uncertainties).

**Comment by joergfunger** [comment]
I see your point, how would the latter be incorporated? Assume the case of a linear model, and we have multiple measurement point along the line. Those are fully correlated, but I'm not sure how this could be incorporated in the likelihood - I guess you probably would have to change the pure adding of the individual loglike contributions, but then the transformation with the log leads to the problem that in theory you would have to a compute the full error vector, apply the covariance of the model correlation). In addition, hwo would you specify this model correlation, since that strongly depends on the model (that we often do not know a priori)?

**Comment by rozsasarpi** [comment]
> how would the latter be incorporated?

As a first step I was thinking about something very concrete, e.g. how it is currently implemented in [taralli](https://gitlab.com/tno-bim/taralli/-/blob/master/taralli/loglikelihood_builder/base.py), that allows to easily build particular covariance matrices.

And a set of data generating processes like those described in [Jan's thesis](https://repository.tudelft.nl/islandora/object/uuid%3A86dd67f0-490e-49e1-ab46-87df1dee307e), section 3.2.

> probably would have to change the pure adding of the individual loglike contributions

If by this you mean the calculation of a loglike term for each measurement and adding them up, then yes.

> hwo would you specify this model correlation, since that strongly depends on the model (that we often do not know a priori)?

I consider the mathematical description of the dependence to be just a model, its parameters can be inferred if needed and multiple models could be considered and selected from (there are some examples of this in Jan's thesis, e.g. section 6.2).
